### ISSUE TITLE
what differences between this and vim-galore

### ISSUE THREAD

**Issue by wsdjeg** [p1v0t/Doctor#3]
I have translate vim-galore into chinese. I want to know what the difference. so I could update the difference into https://github.com/wsdjeg/vim-galore-zh_cn

**Comment by p1v0t** [comment]
I didn't know about [vim-galore](https://github.com/mhinz/vim-galore), (my bad!!!) but it's looks awesome quality of content as well as markdown. Kudos to its authors and contributors. Looks like I have something to learn from it. 

I think both repos have different flavors... I created Doctor as a more practical point of view: "Here is the basics, and add a plugin manager, doesn't work? let's build it from source, it's not that hard." Other thing I see vim-galore is ~3 times longer than Doctor. I don't say it's a bad thing in anyway, just to point out difference. I licensed Doctor in WTFPL while vim-galore uses  CC BY-SA 4.0.
